// Generated by LiveScript 1.3.1
(function(){
  var yjs, delimit, cli, Red, Yellow, fs, ref$, SetConfig, PrintSucess, PrintFailure, Config, WithDir;
  yjs = require("yaml-js");
  delimit = function(it){
    return it.sep;
  }(
  require("path"));
  cli = require("cli-color");
  Red = cli.redBright;
  Yellow = cli.yellowBright;
  fs = require("GetRidOfError")(
  require("fs"));
  ref$ = require("GeneralDev"), SetConfig = ref$.SetConfig, PrintSucess = ref$.PrintSucess, PrintFailure = ref$.PrintFailure;
  Config = {
    InitialExt: "yaml",
    FinalExtention: "json",
    Compile: function(FileName){
      var ReadFilePath;
      ReadFilePath = Config.DirToLook + delimit + FileName + "." + Config.InitialExt;
      return fs.readFile(ReadFilePath, 'utf8', function(data){
        var ParsedYaml, Problem, Json, WriteFilePath;
        try {
          ParsedYaml = yjs.load(data);
        } catch (e$) {
          Problem = e$;
          console.error(Red("Yaml Error:" + Yellow(ReadFilePath)));
          console.error(Red("Line:" + Red("[" + Yellow(Problem.problem_mark.line + Yellow(":" + Yellow(Problem.problem_mark.column + Red("]")))))));
          console.error(Red("Snippet:" + Yellow(Problem.problem_mark.buffer)));
          return;
        }
        Json = JSON.stringify(ParsedYaml, null, 1);
        WriteFilePath = Config.DirToSave + delimit + FileName + "." + Config.FinalExtention;
        fs.writeFile(WriteFilePath, Json, function(){
          PrintSucess(FileName);
        });
      });
    }
  };
  WithDir = function(Init, watch, clean, DirToSave, DirToLook){
    var AutoBuild;
    Init == null && (Init = true);
    watch == null && (watch = true);
    clean == null && (clean = false);
    DirToSave == null && (DirToSave = process.cwd());
    DirToLook == null && (DirToLook = process.cwd());
    Config.DirToSave = DirToSave;
    Config.DirToLook = DirToLook;
    AutoBuild = SetConfig(Config);
    AutoBuild(Init, watch, clean);
  };
  module.exports = WithDir;
}).call(this);
